# -*- coding: utf-8 -*-
"""Logistic Regression for Breast Cancer Tumor classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10RzSkHejKpK415_3kpqHKGg7BbvDbEpk

# Logistic Regression Model

## Importing libraries
"""

import pandas as pd
import numpy as np

"""## Importing the dataset"""

dataset = pd.read_csv('breast_cancer.csv')
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

"""## Splitting dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

print(X_test)

print(y_test)

"""## Training the Logistic Regression model on the Training set"""

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

"""## Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

"""## Computing the accuracy with k-Fold Cross Validation"""

from sklearn.model_selection import cross_val_score
scores = cross_val_score(estimator = classifier, X = X,y = y,cv = 10)
print("Accuracy: {:.2f}%".format(scores.mean()*100))
print("Standard Deviation: {:.2f}%".format(scores.std()*100))